version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - portaudio19-dev

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
