name: matchmaker

channels:
  - anaconda
  - pytorch
  - defaults

dependencies:
  - python=3.9
  - Cython==3.0.0
  - matplotlib==3.8.0
  - numpy==1.26.0
  - pytorch==2.1.0
  - scipy==1.11.3
  - tqdm==4.65.0
  - librosa==0.10.1
  - pip

  - pip:
    - pyaudio==0.2.14
    - fastdtw==0.3.4
    - madmom==0.16.1
    - mido==1.3.0
    - myst-parser>=3.0.1Ø
    - partitura>=1.3.0
    - python-rtmidi==1.5.8
    - pyyaml==6.0.1
    - python-hiddenmarkov==0.1.3
    - Sphinx>=7.4.7
    - sphinx-rtd-theme>=3.0.2